/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportReportIdRouteImport } from './routes/report.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/report/$reportId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  ReportReportIdRoute: ReportReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
